# Generated by Django 5.1.4 on 2025-11-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=50)),
                ('pmfd_date', models.CharField(max_length=10)),
                ('pexp_date', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('pimage', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
