# Generated by Django 5.1.4 on 2025-11-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(max_length=30)),
                ('room_desc', models.CharField(max_length=30)),
                ('price_per_night', models.CharField(max_length=20)),
                ('is_available', models.CharField(max_length=10)),
            ],
        ),
    ]
